### ISSUE TITLE
Optimize Account format

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/Paprika#105]
Currently, when serializing `Account`, the `Nonce` and `Balance` store their lengths using full byte. Taking into consideration total Eth supply and how often nonce is bumped, both values should be capped at `UInt128` or less. Provide a way of storing accounts in an optimized way, where a single byte is used to encode both lengths:

- `0b1000_0000` - mask for marking the special encoding
- `0b0111_0000` - mask for storing the number of bytes for nonce (up to 7 bytes)
- `0b0000_1111` - mask for storing the number of bytes for balance (up to 15 bytes)

This should limit the account size by 1, which is ~2.5% of the total size and can greatly reduce the tree size.

**Comment by CodeBlocker52** [comment]
To store the lengths of the Nonce and Balance fields in an optimized way using a single byte, you can follow the encoding scheme you provided. Here's a breakdown of the encoding scheme:

The first bit (0b1000_0000) is used as a mask to mark the special encoding.
The next four bits (0b0111_0000) are used to store the number of bytes used to encode the Nonce field.
The last four bits (0b0000_1111) are used to store the number of bytes used to encode the Balance field.
Using this encoding scheme, you can store both lengths efficiently in a single byte.
[Nethermind-Paprika-Code.zip](https://github.com/NethermindEth/Paprika/files/11929022/Nethermind-Paprika-Code.zip)

Below attached  the solution code for how you can implement the encoding and decoding functions in Python:

**Comment by Scooletz** [comment]
@CodeBlocker52 For come reason, I missed this comment! Sorry!
