### ISSUE TITLE
Refactor RootPage to just point to DataPage

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/Paprika#118]
Currently, `RootPage` component provides an initial fanout for `DataPage`s. This means that if there's a value with an empty path (see: the root of the Merkle tree) it will have nowhere to go and probably will break the database. By making the `RootPage` just point to the first `DataPage`, the whole situation can be handled in one place, see: `DataPage`. It also makes the `DataPage` responsible for handling fanout etc.

**Comment by lazyfuhrer** [comment]
Assign me @Scooletz

**Comment by Scooletz** [comment]
Hey @lazyfuhrer No need to assign I believe as there's not that much folks pushing to this issue. Happy to see a drafty PR even if it includes only a plan of action for the forthcoming commits.

**Comment by Sah314** [comment]
@Scooletz are all the changes needed only in the RootPage component? , so I can just redirect it to the DataPage component?

**Comment by Scooletz** [comment]
I strongly encourage to read through the design doc accessible here: https://github.com/NethermindEth/Paprika/blob/main/docs/design.md

Answering the question, yes, it looks like it. If we make `RootPage`->`DataPage` it should be much easier to navigate changes later.
