### ISSUE TITLE
Clean allocations in Xor

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/Paprika#192]
#191 introduced great performance gains but added a bit of allocs. It can be removed and pool can be leveraged more. The list of allocations:

- [x] `fp` - in #259 
- [ ] `_fingerprints` (see: [code](https://github.com/NethermindEth/Paprika/blob/cda38d382fd823b4e2dacde6573db344f61d2af5/src/Paprika/Utils/Xor8.cs#L28)) and replacing them with something based on the `BufferPool`

The last one requires constructing a page accessor that would allow to use multiple pages/buffers from the pool and dispose them properly at the end. It could something as simple as `Page[]` as it would already provide a good fanout 1 item -> 4kb of memory.

**Comment by shubham-sonthalia** [comment]
Hi @Scooletz , is this issue still open? I want to work on this.

**Comment by Scooletz** [comment]
Sure thing @shubham-sonthalia !

**Comment by Scooletz** [comment]
Probably going unmanaged with `BufferPool` would be preferable @shubham-sonthalia

**Comment by shubham-sonthalia** [comment]
Okay, so can I use something like this - 

// for allocating memory
IntPtr unmanagedBuffer = Marshal.AllocHGlobal(100 * sizeof(ulong));

and 

// for clearing memory
Marshal.FreeHGlobal(unmanagedBuffer);

**Comment by shubham-sonthalia** [comment]
I have created this PR for one of the bytes array named 'fp'. let me know if this looks correct to you - https://github.com/NethermindEth/Paprika/pull/259

**Comment by shubham-sonthalia** [comment]
Hi @Scooletz, is this issue resolved too?

**Comment by Scooletz** [comment]
@shubham-sonthalia Added one more point, that is `_fingerprints` themselves. If we had this, it would make the Xor much cheaper.

**Comment by shubham-sonthalia** [comment]
Hi @Scooletz, could you confirm if this PR is a right direction  for resolving this issue? - https://github.com/NethermindEth/Paprika/pull/290 

Please advise.

**Comment by Scooletz** [comment]
Xors have been replaced by another mechanism.
