### ISSUE TITLE
RootPage of bigger size

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/Paprika#324]
Currently, the `RootPage` component is the same size as other pages. We could revisit this approach and make it much bigger (8kb, 16kb, 32kb...) and scale up the structures it contains. Potential benefits and applications:

1. shorter paths in the tree
2. shorter lookup for contract ids
3. bigger `AbandonedList`
4. adding some SlottedArray at the root

To make it work for experiments, the following steps should be taken:

- [ ] Preparation
   - [ ] detach `RootPage` from `Page`
   - [ ] `IPageManager.FlushRootPage` and implementations needs to be revisit to take the new size into consideration. Also, as writing multiple pages is not atomic, use the 0th page as the index to what was the last write.
   - [ ] `PagedDb._pooledRoots` cannot be based on the `BufferPool` which uses 4k pages or `BufferPool` should be made configurable
   - [ ] `PagedDb` and `NextFreePage` calculations, should start at `N + RootPage.Size`
- [ ] Experiments
   - [ ] Use `Paprika.Runner` to show differences
   - [ ] Use tests to show differences
   - [ ] Use `Benchmarks` to show differences

**Comment by murluki** [comment]
Could you assign it to me, please?

**Comment by Scooletz** [comment]
After #397 there's no need to have it changed and use a different root.
