### ISSUE TITLE
Support branching NewPayloads in Engine API

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/Paprika#67]
In Engine API we can get branching payloads.
![image](https://user-images.githubusercontent.com/12445221/235879340-4694cd83-9bbc-4f99-9cec-57285644f45c.png)
https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#engine_newpayloadv1

So we can get NewPayloads from different branches. We need to be able to respond Valid/Invalid from canonical branch. We can respond Accepted from non-canonical branch. Canonical branch is an arbitrary one that is on top of the head designated by the FCU.

Currently Nethermind responds Valid/Invalid also from non-canonical branches as it can keep multiple roots on same block level, it is simpler and allows CL to work optimally. 

Consider if this requirements can be met with paprika. If not we will need to switch to accepted for non-canonical branches.

If we will use to Accepted, we need to process blocks in FCU to validate them properly.

**Comment by Scooletz** [comment]
The issue is worked on at #88 that will provide it. More comments in the PR

**Comment by Scooletz** [comment]
Provided in #88
